#!/usr/bin/env php
<?php

/**
 * Command line interface for console jobs.
 *
 * @author Gigablah <gigablah@vgmdb.net>
 */

set_time_limit(0);

$app = call_user_func(function (array $options) {
    chdir($options['base_dir']);

    $autoloader = require($options['base_dir'] . '/app/bootstrap.php');

    $input = new Symfony\Component\Console\Input\ArgvInput();

    $env = $input->getParameterOption(array('--env', '-e'), getenv('HOST_ENV') ?: 'dev');
    $debug = getenv('HOST_DEBUG') !== '0' && !$input->hasParameterOption('--no-debug') && $env !== 'prod';
    $app_name = $input->getParameterOption('--app', 'vgmdb');
    $cache = $input->hasParameterOption('--enable-cache');

    $container = require($options['base_dir'] . '/app/app.php');
    $container['shell.class'] = 'VGMdb\\Component\\Console\\Shell';

    $container['command.classmap'] = array();

    return new VGMdb\Component\Console\Application($container, 'VGMdb', '1.0.0');
}, array(
    'base_dir' => dirname(__DIR__)
));

$app->run(new Symfony\Component\Console\Input\ArgvInput());
