<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <style>
      /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
      html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}
      img { border: 0; }
      #sf-resetcontent { width:970px; margin:0 auto; }
      html {
        margin: 0;
        padding: 0;
        background-color: white;
      }
      body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 14px;
        text-rendering: optimizeLegibility;
        margin: 0;
        padding: 0;
        color: #333;
        background-color: white;
      }
      .container {
        margin-right: auto;
        margin-left: auto;
        width: 940px;
      }
      pre {
        display: block;
        padding: 9.5px;
        margin: 10px 0;
        font-size: 13px;
        line-height: 20px;
        white-space: pre;
        white-space: pre-wrap;
        background-color: whiteSmoke;
        border: 1px solid #CCC;
        border: 1px solid rgba(0, 0, 0, 0.15);
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
      }
      code {
        padding: 2px 4px;
        color: #D14;
        white-space: nowrap;
        background-color: #F7F7F9;
        border: 1px solid #E1E1E8;
        font-size: 15px;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
      }
      blockquote {
        padding: 0 0 0 15px;
        margin: 0 0 20px;
        border-left: 5px solid #EEE;
        font-size: 16px;
        font-weight: 300;
        line-height: 22px;
      }
      blockquote.alert {
        border-left: 5px solid #B94A48;
        color: #B94A48;
      }
      .header {
        padding: 20px 0;
        margin-bottom: 20px;
        background-color: whiteSmoke;
        border-bottom: 1px solid #E5E5E5;
      }
      .center {
        margin: 40px auto;
        display: block;
      }
      p {
        line-height: 24px;
      }
      h1 {
        font-size: 30px;
        color: black;
        line-height: 32px;
        text-shadow: 1px 1px 0 white;
        letter-spacing: -1px;
        font-weight: bold;
      }
      h2 {
        font-size: 16px;
        line-height: 20px;
        font-weight: bold;
        margin: 20px 0;
      }
      ul {
        list-style-type: square;
        margin: 16px 0;
      }
      ul li {
        list-style-type: square;
        list-style-position:inside;
      }
      ol {
        list-style-type: decimal;
      }
      ol li {
        display: list-item;
        text-align: -webkit-match-parent;
        list-style-type: decimal;
        line-height: 20px;
      }
      abbr {
        border-bottom: 1px dotted #333;
      }
      .xdebug-error {
        display: none;
      }
      br {
        display: none;
      }
    </style>
    <title>404 Page Not Found</title>
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>Sorry, the page you are looking for could not be found.</h1>
        </div>
    </header>
    <div id="container" class="container">
        <p>We tried looking, but it's just not there.</p>
    </div>
</body>
</html>
