# Sends Cross-Origin Resource Sharing headers based on subdomain and path.

services:
    cors:
        provider: VGMdb\Component\Cors\CorsServiceProvider
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
        config:
            -
                path: ^/
                host: [ %app.hosts.internal.host%, %app.hosts.api.host% ]
                allow_origin: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
